export const GET_ADMIN_USERS_ATTEMPT = "GET_ADMIN_USERS_ATTEMPT";
export const GET_ADMIN_USERS_SUCCESS = "GET_ADMIN_USERS_SUCCESS";
export const GET_ADMIN_USERS_FAIL = "GET_ADMIN_USERS_FAIL";

export const GET_PROMO_CODES_ATTEMPT = "GET_PROMO_CODES_ATTEMPT";
export const GET_PROMO_CODES_SUCCESS = "GET_PROMO_CODES_SUCCESS";
export const GET_PROMO_CODES_FAIL = "GET_PROMO_CODES_FAIL";

export const CREATE_PROMO_CODES_ATTEMPT = "CREATE_PROMO_CODES_ATTEMPT";
export const CREATE_PROMO_CODES_SUCCESS = "CREATE_PROMO_CODES_SUCCESS";
export const CREATE_PROMO_CODES_FAIL = "CREATE_PROMO_CODES_FAIL";

export const UPDATE_PROMO_CODES_ATTEMPT = "UPDATE_PROMO_CODES_ATTEMPT";
export const UPDATE_PROMO_CODES_SUCCESS = "UPDATE_PROMO_CODES_SUCCESS";
export const UPDATE_PROMO_CODES_FAIL = "UPDATE_PROMO_CODES_FAIL";

export const DELETE_PROMO_CODES_ATTEMPT = "DELETE_PROMO_CODES_ATTEMPT";
export const DELETE_PROMO_CODES_SUCCESS = "DELETE_PROMO_CODES_SUCCESS";
export const DELETE_PROMO_CODES_FAIL = "DELETE_PROMO_CODES_FAIL";

export const NOTIFICATION_BROADCASTING_ATTEMPT =
  "NOTIFICATION_BROADCASTING_ATTEMPT";
export const NOTIFICATION_BROADCASTING_SUCCESS =
  "NOTIFICATION_BROADCASTING_SUCCESS";
export const NOTIFICATION_BROADCASTING_FAIL = "NOTIFICATION_BROADCASTING_FAIL";

export const ASSIGN_PROMO_SUCCESS = "ASSIGN_PROMO_SUCCESS";

export const UPDATE_ACTIVE_STATUS = "UPDATE_ACTIVE_STATUS";
