import { dictionary } from "../languageSwitch";
export const ServerUrl = "https://testing.egenienext.com:3004";
export const ServerUrlVendor = "https://testing.egenienext.com:3005";
export const ServerUrlProduct = "https://testing.egenienext.com:3007";
export const ServerUrlFile = "https://testing.egenienext.com:3011";
export const ServerUrlCustomer = "https://testing.egenienext.com:3014";
export const ServerUrlOrder = "https://testing.egenienext.com:3016";
export const ServerUrlEmployees = "https://testing.egenienext.com:3022";
export const ServerUrlBills = "https://testing.egenienext.com:3020";
export const ServerUrlFileHandler = "https://testing.egenienext.com:3011";
export const ServerUrlNotificatons = "https://testing.egenienext.com:3009";
export const ServerUrlAnalysis = "https://testing.egenienext.com:3024";
export const ServerUrlReports = "https://testing.egenienext.com:3024";
let endpoints = {};
window.translate = {};

export function _(val, lang) {
  // lang = "ar";
  if (lang === "ar" && dictionary[val] !== undefined) {
    return dictionary[val];
  } else if (lang === "ar" && dictionary[val] === undefined) {
    // window.translate[val] = "";
    // return val + "..Not Avail";
    // return val + "..Not available";
  }
  return val;
}

// export function LocalizedStrings({
//   en: {
//     Countries: [
//       "Afghanistan",
//       "Albania",
//       "Algeria",
//       "American Samoa",
//       "Andorra",
//       "Angola",
//       "Anguilla",
//       "Antarctica",
//       "Antigua And Barbuda",
//       "Argentina",
//       "Armenia",
//       "Aruba",
//       "Australia",
//       "Austria",
//       "Azerbaijan",
//       "Bahamas",
//       "Bahrain",
//       "Bangladesh",
//       "Barbados",
//       "Belarus",
//       "Belgium",
//       "Belize",
//       "Benin",
//       "Bermuda",
//       "Bhutan",
//       "Bolivia",
//       "Bosnia And Herzegovina",
//       "Botswana",
//       "Bouvet Island",
//       "Brazil",
//       "British Indian Ocean Territory",
//       "Brunei Darussalam",
//       "Bulgaria",
//       "Burkina Faso",
//       "Burundi",
//       "Cambodia",
//       "Cameroon",
//       "Canada",
//       "Cape Verde",
//       "Cayman Islands",
//       "Central African Republic",
//       "Chad",
//       "Chile",
//       "China",
//       "Christmas Island",
//       "Cocos (keeling) Islands",
//       "Colombia",
//       "Comoros",
//       "Congo",
//       "Congo, The Democratic Republic Of The",
//       "Cook Islands",
//       "Costa Rica",
//       "Cote D'ivoire",
//       "Croatia",
//       "Cuba",
//       "Cyprus",
//       "Czech Republic",
//       "Denmark",
//       "Djibouti",
//       "Dominica",
//       "Dominican Republic",
//       "East Timor",
//       "Ecuador",
//       "Egypt",
//       "El Salvador",
//       "Equatorial Guinea",
//       "Eritrea",
//       "Estonia",
//       "Ethiopia",
//       "Falkland Islands (malvinas)",
//       "Faroe Islands",
//       "Fiji",
//       "Finland",
//       "France",
//       "French Guiana",
//       "French Polynesia",
//       "French Southern Territories",
//       "Gabon",
//       "Gambia",
//       "Georgia",
//       "Germany",
//       "Ghana",
//       "Gibraltar",
//       "Greece",
//       "Greenland",
//       "Grenada",
//       "Guadeloupe",
//       "Guam",
//       "Guatemala",
//       "Guinea",
//       "Guinea-bissau",
//       "Guyana",
//       "Haiti",
//       "Heard Island And Mcdonald Islands",
//       "Holy See (vatican City State)",
//       "Honduras",
//       "Hong Kong",
//       "Hungary",
//       "Iceland",
//       "India",
//       "Indonesia",
//       "Iran, Islamic Republic Of",
//       "Iraq",
//       "Ireland",
//       "Israel",
//       "Italy",
//       "Jamaica",
//       "Japan",
//       "Jordan",
//       "Kazakstan",
//       "Kenya",
//       "Kiribati",
//       "Korea, Democratic People's Republic Of",
//       "Korea, Republic Of",
//       "Kosovo",
//       "Kuwait",
//       "Kyrgyzstan",
//       "Lao People's Democratic Republic",
//       "Latvia",
//       "Lebanon",
//       "Lesotho",
//       "Liberia",
//       "Libyan Arab Jamahiriya",
//       "Liechtenstein",
//       "Lithuania",
//       "Luxembourg",
//       "Macau",
//       "Macedonia, The Former Yugoslav Republic Of",
//       "Madagascar",
//       "Malawi",
//       "Malaysia",
//       "Maldives",
//       "Mali",
//       "Malta",
//       "Marshall Islands",
//       "Martinique",
//       "Mauritania",
//       "Mauritius",
//       "Mayotte",
//       "Mexico",
//       "Micronesia, Federated States Of",
//       "Moldova, Republic Of",
//       "Monaco",
//       "Mongolia",
//       "Montserrat",
//       "Montenegro",
//       "Morocco",
//       "Mozambique",
//       "Myanmar",
//       "Namibia",
//       "Nauru",
//       "Nepal",
//       "Netherlands",
//       "Netherlands Antilles",
//       "New Caledonia",
//       "New Zealand",
//       "Nicaragua",
//       "Niger",
//       "Nigeria",
//       "Niue",
//       "Norfolk Island",
//       "Northern Mariana Islands",
//       "Norway",
//       "Oman",
//       "Pakistan",
//       "Palau",
//       "Palestinian Territory, Occupied",
//       "Panama",
//       "Papua New Guinea",
//       "Paraguay",
//       "Peru",
//       "Philippines",
//       "Pitcairn",
//       "Poland",
//       "Portugal",
//       "Puerto Rico",
//       "Qatar",
//       "Reunion",
//       "Romania",
//       "Russian Federation",
//       "Rwanda",
//       "Saint Helena",
//       "Saint Kitts And Nevis",
//       "Saint Lucia",
//       "Saint Pierre And Miquelon",
//       "Saint Vincent And The Grenadines",
//       "Samoa",
//       "San Marino",
//       "Sao Tome And Principe",
//       "Saudi Arabia",
//       "Senegal",
//       "Serbia",
//       "Seychelles",
//       "Sierra Leone",
//       "Singapore",
//       "Slovakia",
//       "Slovenia",
//       "Solomon Islands",
//       "Somalia",
//       "South Africa",
//       "South Georgia And The South Sandwich Islands",
//       "Spain",
//       "Sri Lanka",
//       "Sudan",
//       "Suriname",
//       "Svalbard And Jan Mayen",
//       "Swaziland",
//       "Sweden",
//       "Switzerland",
//       "Syrian Arab Republic",
//       "Taiwan, Province Of China",
//       "Tajikistan",
//       "Tanzania, United Republic Of",
//       "Thailand",
//       "Togo",
//       "Tokelau",
//       "Tonga",
//       "Trinidad And Tobago",
//       "Tunisia",
//       "Turkey",
//       "Turkmenistan",
//       "Turks And Caicos Islands",
//       "Tuvalu",
//       "Uganda",
//       "Ukraine",
//       "United Arab Emirates",
//       "United Kingdom",
//       "United States",
//       "United States Minor Outlying Islands",
//       "Uruguay",
//       "Uzbekistan",
//       "Vanuatu",
//       "Venezuela",
//       "Viet Nam",
//       "Virgin Islands, British",
//       "Virgin Islands, U.s.",
//       "Wallis And Futuna",
//       "Western Sahara",
//       "Yemen",
//       "Zambia",
//       "Zimbabwe"
//     ],
//     ProductNameAlert: "Product name must have at least 3 characters.",
//     ProductNameRequired: "Product name is Required.",
//     ProductCreateAlert: "Product created successfully.",
//     ProductUpdateAlert: "Product updated successfully.",
//     ProductNotCreateAlert: "Product could not be created.",
//     EmptyNameError: "Product name should not be empty.",
//     AlreadySku: "This sku is already taken.",
//     UpdateQuantity: "Update Quantity.",
//     Update: "Update",
//     ExpectedDate: "Expected Date of Replenishment.",
//     VariantError: "Only 3 variants are allowed.",
//     EmptySku: "SKU should not be empty.",
//     ItemError: "Item should not be empty.",
//     ItemLimitAlert: "Only 10 items are allowed.",
//     Error: "Error",
//     CategoryError: "Please Select Category.",
//     Replenished: "Replenished",
//     RequestedReplenishment: "Requested Replenishment",
//     Discontinued: "Discontinued",
//     Status: "Status",
//     InStock: "in stock",
//     QuantityError: "Quantity should not be empty.",
//     SaveMore: "SAVE & MORE",
//     Save: "SAVE",
//     SaveClose: "SAVE & CLOSE",
//     Discard: "DISCARD",
//     ItemAlert: "Minimum two items are allowed.",
//     RequiredAlert: "Please enter required fields",
//     OptionAlert: "Only 8 elements are allowed.",
//     EnterQty: "Enter Qty",
//     Size: "xs,s,m,lg,xl,xxl",
//     labelName: "Label Name:",
//     CreateUnit: "Create new unit",
//     CreateProvider: "Create new Provider",
//     color: "Color: ",
//     addLabel: "Add Label",
//     editLabel: "Edit Label",
//     ServiceInformation: "Service Information",
//     Provider: "Provider",
//     Item: "Item",
//     AddMore: "Add More",
//     ServiceProviderInformation: "Service Provider Information",
//     PackageInformation: "Package Information",
//     PackageItems: "Package Items",
//     delete: "Delete",
//     edit: "Edit",
//     PriceRange: "Price Range",
//     options: "Options",

//     OptionText: "Enter option name separated by comma (Maximum is 8)",
//     create: "Create New",
//     UnitPrice: "UnitPrice",
//     Qty: "Qty",
//     NoData: "No Data",
//     AddPatches: "Add More Patches",
//     PatchesDetail: "Patches Detail",
//     ProductDetail: "Product Detail",
//     productInformation: "Product Information",
//     VariantInformation: "Variant Information",
//     sku: "SKU",
//     EnterAmount: "Enter Amount",
//     reset: "Reset",
//     apply: "Apply",
//     Phone: "Phone",
//     PhoneNo: "Phone No.",
//     UnitType: "Unit Type",
//     Type: "Type",
//     PricingInformation: "Pricing Information",
//     PerDay: "Per Day",
//     Days: "Days",
//     Close: "CLOSE",
//     ProductGroupName: "Product Group Name",
//     VendorName: "Vendor Name",
//     QuantityDetail: "Quantity Details",
//     Quantity: "Quantity",
//     Language: "Language",
//     Available: "Available",
//     MinimumThreshold: "Minimum Threshold",
//     Threshold: "Threshold",
//     PurchaseDate: "Purchase Date",
//     ExpirationDate: "Expiration Date",
//     Exp: "Exp.",
//     VAT: "VAT",
//     VATAccNo: "Vat Acc. No.",
//     VATRate: "VAT Rate",
//     CommercialRegistrationNumber: "Commercial Registration Number (CRN)",
//     Cost: "Cost and Pricing",
//     Add: "Add",
//     Included: "Included",
//     CostUnit: "Cost/Unit",
//     CostPackage: "Cost/Package",
//     SAR: "SAR",
//     SearchOrCreateCategory: "Search or create category",
//     PriceUnit: "Price/Unit",
//     PricePackage: "Price/Package",
//     TotalCost: "Total Cost",
//     Patch: "Patch",
//     With: "with",
//     Without: "without",
//     Label: "Label",
//     Website: "Website",
//     SelectCategory: "Select Category",
//     SelectTheme: "Select Theme",
//     SelectVendor: "Select Vendor",
//     SelectUnit: "Select Unit",
//     StreetAddress1: "Street Address 1",
//     StreetAddress2: "Street Address 2",
//     BusinessAddress: "Business Address",
//     City: "City",
//     State: "State",
//     SocialMedia: "Social Media",
//     PostalCode: "Postal Code",
//     UpdateForm: "Update Form",
//     WorkingSchedule: "Working Schedule",
//     WorkingDays: "Working Days",
//     ReligiousHolidays: "Religious Holidays",
//     Country: "Country",
//     Light: "Light",
//     Dark: "Dark(Night mode)",
//     UpdateFormString:
//       "Add to reminder to remind if the products have been delivered",
//     Note: "Note",
//     Email: "Email Address",
//     SelectCountry: "Select Country",
//     MaxNoteCharacters: "Maximum 100 characters",
//     EmailExample: "Ex: info@example.com",
//     MobileNo: "Mobile No.",
//     Work: "Work",
//     Home: "Home",
//     Main: "Main",
//     Model: "Model No.",
//     Category: "Category",
//     Fax: "Fax",
//     Custom: "Custom",
//     Other: "Other",
//     ChangeType: "Change Type",
//     Signup: "SIGN UP",
//     Login: "Log in",
//     Logout: "Log out",
//     Name: "Name",
//     Ignore: "Ignore",
//     FullName: "Full Name",
//     Ignored: "Ignored",
//     FirstName: "First Name",
//     LastName: "Last Name",
//     Active: "Active",
//     OrderDate: "Order Date",
//     DateOfBirth: "Date of Birth",
//     BusinessInformation: "Business Information",
//     BusinessName: "Business Name",
//     Discounted: "Discounted",
//     OnBackOrder: "On Back Order",
//     OutOfStock: "Out Of Stock",
//     LowStock: "Low Stock",
//     IncludeOnHold: "Include On Hold Items",
//     Password: "Password",
//     RetypePassword: "Retype Password",
//     CreateAccount: "Create New Account",
//     AlreadyHaveAccount: "Already Have an Account?",
//     NewUser: "New User?",
//     CreateYourAccount: "Create your account for free.",
//     ForgotPassword: "Forgot password?",
//     WelcomeBack: "Welcome back!",
//     Agreement: "I agree to the",
//     TOS: "Terms of Service",
//     And: "and",
//     SelectProduct: "Select Product",
//     Providers: "Providers",
//     SelectProvider: "Select Provider",
//     SelectVariantCategory: "Select Variant Category",
//     AddMoreVariants: "Add More Variants",
//     PrivacyPolicy: "Privacy Policy",
//     OrLoginUsing: "Or log in using",
//     English: "English",
//     Arabic: "Arabic",
//     completeTheForm: "Please complete the form.",
//     displayNameError: "Name should have at least 5 characters.",
//     displayEmailError: "Email ID is not in correct format.",
//     displayPasswordError:
//       "Password must contain minimum eight characters, one number and one special character.",
//     displayRetypePasswordError: "Password fields do not match.",
//     TosIsNotChecked:
//       "Please accept the TOS and Privacy Policy before submitting the form",
//     RegistrationSuccessful:
//       "Registration successful. A verification email sent to your account.",
//     Confirm: "Confirm",
//     Cancel: "Cancel",
//     OnHold: "On Hold",
//     OnHoldSmall: "on hold",
//     Dashboard: "Dashboard",
//     EnterCode: "Enter Code",
//     Orders: "Orders",
//     Bills: "Bills",
//     Reports: "Reports",
//     ProductsServices: "Products/Services",
//     PreOrder: "Pre Order",
//     PreOrderSmall: "pre order",
//     Customers: "Customers",
//     Vendors: "Vendors",
//     Vendor: "Vendor",
//     VendorAdd: "Add new vendor",
//     VendorEdit: "Edit vendor",
//     VendorDetail: "Vendor Detail",
//     Employees: "Employees",
//     Analysis: "Analysis",
//     End: "End",
//     NoOfEmployee: "No. of Employee",
//     LastBillDate: "Last Bill Date",
//     LastBillNo: "Last Bill No.",
//     LastTransaction: "Last transaction:",
//     LastUpdated: "Last Updated",
//     NotRecorded: "Not recorded",
//     PersonalInformation: "Personal Information",

//     ContactSupport: "Contact us/Support",
//     VendorInformation: "Vendor\nInformation",
//     RepresentativesInformation: "Representatives\nInformation",
//     VendorHistory: "Vendor\nHistory",
//     AddLabel: "Add Label",
//     TransactionDate: "Transaction Date",
//     StartDate: "Start Date",
//     Start: "Start",
//     NewEmail: "New Email",
//     SecondaryEmail: "Secondary Email Address",
//     EnableAuthentication: "Enable Two-factor Authentication",
//     SendCode: "Send Test Code",
//     GeneralSettings: "General Settings",
//     ChangePasswordOrEmail: "Change Password / Email Address",
//     ChangePassword: "Change Password",
//     CurrentPassword: "Current Password",
//     NewPassword: "New Password",
//     ConfirmPassword: "Confirm Password",
//     ChangeEmail: "Change Email Address",
//     CurrentEmail: "Current Email",
//     Regional: "Regional",
//     NumberFormat: "Number Format",
//     DateFormat: "Date Format",
//     TimeZone: "Time Zone",
//     StartPage: "Start Page",
//     Currency: "Currency",
//     DefaultVAT: "Dafault VAT",
//     DefaultLanguage: "Default Language",
//     DefaultPage: "Default Page",
//     EndDate: "End Date",
//     SelectDate: "Select Date",
//     FilterByLabel: "Filter By Label",
//     SelectLabel: "Select Label",
//     Apply: "Apply",
//     Reset: "Reset",
//     AddNew: "Add new",
//     ProductEdit: "Edit Product",
//     ProductType: "Product Type",
//     Product: "Product",
//     Variant: "Variant",
//     Variants: "Variants",
//     Service: "Service",
//     Package: "Package",
//     Packages: "Packages",
//     Settings: "Settings",
//     UserProfile: "User Profile",
//     Themes: "Themes",
//     SignInAndSecurity: "SignIn & Security",
//     Preferences: "Preferences",
//     AdditionalUsers: "Additional Users",
//     userProfileUpdateMessage: "User profile has been updated successfully."
//   },
//   ar: {
//     Countries: [
//       "أفغانستان",
//       "ألبانيا",
//       "الجزائر",
//       "ساموا الأمريكية",
//       "أندورا",
//       "أنغولا",
//       "أنغيلا",
//       "القارة القطبية الجنوبية",
//       "أنتيغوا وبربودا",
//       "الأرجنتين",
//       "أرمينيا",
//       "أروبا",
//       "أستراليا",
//       "النمسا",
//       "أذربيجان",
//       "الباهاما",
//       "البحرين",
//       "بنغلاديش",
//       "بربادوس",
//       "روسيا البيضاء",
//       "بلجيكا",
//       "بليز",
//       "بنين",
//       "برمودا",
//       "بوتان",
//       "بوليفيا",
//       "البوسنة والهرسك",
//       "بوتسوانا",
//       "جزيرة بوفيت",
//       "البرازيل",
//       "إقليم المحيط البريطاني الهندي",
//       "بروناي دار السلام",
//       "بلغاريا",
//       "بوركينا فاسو",
//       "بوروندي",
//       "كمبوديا",
//       "الكاميرون",
//       "كندا",
//       "الرأس الأخضر",
//       "جزر كايمان",
//       "جمهورية افريقيا الوسطى",
//       "تشاد",
//       "تشيلي",
//       "الصين",
//       "جزيرة الكريسماس",
//       "جزر كوكوس",
//       "كولومبيا",
//       "جزر القمر",
//       "الكونغو",
//       "جمهورية الكونغو الديمقراطية",
//       "جزر كوك",
//       "كوستا ريكا",
//       '"كوت ديفوار"،',
//       "كرواتيا",
//       "كوبا",
//       "قبرص",
//       "جمهورية التشيك",
//       "الدنمارك",
//       "جيبوتي",
//       "دومينيكا",
//       "جمهورية الدومنيكان",
//       "تيمور الشرقية",
//       "الإكوادور",
//       "مصر",
//       "السلفادور",
//       "غينيا الإستوائية",
//       "إريتريا",
//       "استونيا",
//       "أثيوبيا",
//       "جزر فوكلاند (مالفيناس)",
//       "جزر فاروس",
//       "فيجي",
//       "فنلندا",
//       "فرنسا",
//       "غيانا الفرنسية",
//       "بولينيزيا الفرنسية",
//       "المناطق الجنوبية لفرنسا",
//       "الغابون",
//       "غامبيا",
//       "جورجيا",
//       "ألمانيا",
//       "غانا",
//       "جبل طارق",
//       "اليونان",
//       "الأرض الخضراء",
//       "غرينادا",
//       "جوادلوب",
//       "غوام",
//       "غواتيمالا",
//       "غينيا",
//       "غينيا بيساو",
//       "غيانا",
//       "هايتي",
//       "قلب الجزيرة وجزر ماكدونالز",
//       "الكرسي الرسولي (دولة الفاتيكان)",
//       "هندوراس",
//       "هونغ كونغ",
//       "هنغاريا",
//       "أيسلندا",
//       "الهند",
//       "إندونيسيا",
//       "جمهورية إيران الإسلامية من",
//       "العراق",
//       "أيرلندا",
//       "إسرائيل",
//       "إيطاليا",
//       "جامايكا",
//       "اليابان",
//       "الأردن",
//       "كازاخستان",
//       "كينيا",
//       "كيريباس",
//       '"كوريا، الجمهورية الشعبية الديمقراطية"،',
//       "جمهورية كوريا",
//       "كوسوفو",
//       "الكويت",
//       "قرغيزستان",
//       '"جمهورية لاو الديمقراطية الشعبية"،',
//       "لاتفيا",
//       "لبنان",
//       "ليسوتو",
//       "ليبيريا",
//       "الجماهيرية العربية الليبية",
//       "ليختنشتاين",
//       "ليتوانيا",
//       "لوكسمبورغ",
//       "ماكاو",
//       "مقدونيا، جمهورية يوغوسلافيا السابقة",
//       "مدغشقر",
//       "مالاوي",
//       "ماليزيا",
//       "جزر المالديف",
//       "مالي",
//       "مالطا",
//       "جزر مارشال",
//       "مارتينيك",
//       "موريتانيا",
//       "موريشيوس",
//       "مايوت",
//       "المكسيك",
//       "ولايات ميكرونيزيا الموحدة من",
//       "جمهورية مولدوفا",
//       "موناكو",
//       "منغوليا",
//       "مونتسيرات",
//       "الجبل الأسود",
//       "المغرب",
//       "موزمبيق",
//       "ميانمار",
//       "ناميبيا",
//       "ناورو",
//       "نيبال",
//       "هولندا",
//       "جزر الأنتيل الهولندية",
//       "كاليدونيا الجديدة",
//       "نيوزيلاندا",
//       "نيكاراغوا",
//       "النيجر",
//       "نيجيريا",
//       "نيوي",
//       "جزيرة نورفولك",
//       "جزر مريانا الشمالية",
//       "النرويج",
//       "سلطنة عمان",
//       "باكستان",
//       "بالاو",
//       "الأراضي الفلسطينية المحتلة",
//       "بناما",
//       "بابوا غينيا الجديدة",
//       "باراغواي",
//       "بيرو",
//       "الفلبين",
//       "بيتكيرن",
//       "بولندا",
//       "البرتغال",
//       "بورتوريكو",
//       "دولة قطر",
//       "جمع شمل",
//       "رومانيا",
//       "الاتحاد الروسي",
//       "رواندا",
//       "سانت هيلانة",
//       "سانت كيتس ونيفيس",
//       "القديسة لوسيا",
//       "سانت بيير وميكلون",
//       "سانت فنسنت وجزر غرينادين",
//       "ساموا",
//       "سان مارينو",
//       "ساو تومي وبرينسيبي",
//       "المملكة العربية السعودية",
//       "السنغال",
//       "صربيا",
//       "سيشيل",
//       "سيرا ليون",
//       "سنغافورة",
//       "سلوفاكيا",
//       "سلوفينيا",
//       "جزر سليمان",
//       "الصومال",
//       "جنوب أفريقيا",
//       "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
//       "إسبانيا",
//       "سيريلانكا",
//       "السودان",
//       "سورينام",
//       "سفالبارد",
//       "سوازيلاند",
//       "السويد",
//       "سويسرا",
//       "الجمهورية العربية السورية",
//       "مقاطعة تايوان الصينية",
//       "طاجيكستان",
//       "جمهورية تنزانيا المتحدة",
//       "تايلاند",
//       "توجو",
//       "توكيلاو",
//       "تونغا",
//       "ترينداد وتوباغو",
//       "تونس",
//       "ديك رومي",
//       "تركمانستان",
//       "جزر تركس وكايكوس",
//       "توفالو",
//       "أوغندا",
//       "أوكرانيا",
//       "الإمارات العربية المتحدة",
//       "المملكة المتحدة",
//       "الولايات المتحدة الأمريكية",
//       "جزر الولايات المتحدة البعيدة الصغرى",
//       "أوروغواي",
//       "أوزبكستان",
//       "فانواتو",
//       "فنزويلا",
//       "فيتنام",
//       "جزر العذراء البريطانية",
//       "جزر فيرجن، الولايات المتحدة",
//       "واليس وفوتونا",
//       "الصحراء الغربية",
//       "اليمن",
//       "زامبيا",
//       "زيمبابوي"
//     ],
//     ProductNameAlert: "يجب أن يكون اسم المنتج 3 أحرف على الأقل.",
//     ProductNameRequired: "اسم المنتج هو مطلوب.",
//     ProductCreateAlert: "خلق المنتج بنجاح.",
//     ProductUpdateAlert: "المنتج تحديثها بنجاح.",
//     ProductNotCreateAlert: "لا يمكن إنشاء المنتج.",
//     EmptyNameError: "لا ينبغي أن يكون اسم المنتج فارغة.",
//     AlreadySku: "يؤخذ هذا سكو بالفعل.",
//     UpdateQuantity: "تحديث الكمية.",
//     Update: "تحديث",
//     ExpectedDate: "التاريخ المتوقع للتجديد.",
//     VariantError: "ويسمح فقط 3 المتغيرات.",
//     EmptySku: "يجب SKU لا يكون فارغا.",
//     ItemError: "البند يجب أن لا تكون فارغة.",
//     ItemLimitAlert: "ويسمح للمادة 10 فقط.",
//     Error: "خطأ",
//     CategoryError: "الرجاء اختيار الفئة.",
//     Replenished: "تجديد",
//     RequestedReplenishment: "التجديد المطلوبة",
//     Discontinued: "توقف",
//     Status: "الحالة",
//     InStock: "في المخزن",
//     QuantityError: "لا ينبغي أن تكون الكمية فارغة.",
//     SaveMore: "احفظ أكثر",
//     Save: "حفظ",
//     SaveClose: "حفظ وإغلاق",
//     Discard: "تجاهل",
//     ItemAlert: "يسمح البنود الحد الأدنى اثنين.",
//     RequiredAlert: "الرجاء إدخال الحقول المطلوبة",
//     OptionAlert: "يسمح العناصر 8 فقط.",
//     EnterQty: "أدخل الكمية",
//     Size: "XS، S، M، L، XL، XXL",
//     labelName: "اسم الطابع:",
//     CreateUnit: "إنشاء وحدة جديدة",
//     CreateProvider: "إنشاء مزود جديد",
//     color: "اللون:",
//     addLabel: "إضافة تسمية",
//     editLabel: "تحرير تسمية",
//     ServiceInformation: "معلومات الخدمة",
//     Provider: "مزود",
//     Item: "بند",
//     AddMore: "أضف المزيد",
//     ServiceProviderInformation: "معلومات مقدم الخدمة",
//     PackageInformation: "حزمة معلومات",
//     PackageItems: "حزمة البنود",
//     delete: "حذف",
//     edit: "تعديل",
//     options: "خيارات",
//     OptionText: "أدخل اسم الخيار مفصولة بفواصل (الحد الأقصى هو 8)",
//     create: "خلق جديد إبداع جديد",
//     UnitPrice: "سعر الوحده",
//     Qty: "الكمية",
//     NoData: "لايوجد بيانات",
//     AddPatches: "إضافة المزيد من الرقع",
//     PatchesDetail: "بقع التفاصيل",
//     ProductDetail: "تفاصيل المنتج",
//     productInformation: "معلومات المنتج",
//     VariantInformation: "معلومات البديل",
//     sku: "SKU",
//     EnterAmount: "أدخل المبلغ",
//     reset: "إعادة تعيين",
//     apply: "تطبيق",
//     Phone: "هاتف",
//     PhoneNo: "رقم الهاتف.",
//     UnitType: "نوع الوحدة",
//     Type: "اكتب",
//     PricingInformation: "معلومات التسعير",
//     PerDay: "في اليوم",
//     Close: "أغلق",
//     ProductGroupName: "اسم المنتج المجموعة",
//     VendorName: "اسم البائع",
//     QuantityDetail: "الكمية تفاصيل",
//     Quantity: "كمية",
//     Available: "متاح",
//     MinimumThreshold: "الحد الأدنى عتبة",
//     Threshold: "عتبة",
//     PurchaseDate: "تاريخ الشراء",
//     ExpirationDate: "تاريخ إنتهاء الصلاحية",
//     Exp: "إكسب.",
//     VAT: "ضريبة",
//     VATAccNo: "ضريبة القيمة المضافة لجنة التنسيق الإدارية. لا.",
//     VATRate: "قيمة الضريبة",
//     CommercialRegistrationNumber: "السجل التجاري رقم (CRN)",
//     Cost: "التكلفة والتسعير",
//     Add: "إضافة",
//     Included: "شمل",
//     CostUnit: "وحدة التكلفة",
//     CostPackage: "التكلفة / حزمة",
//     SAR: "SAR",
//     SearchOrCreateCategory: "بحث أو إنشاء فئة",
//     PriceUnit: "السعر / وحدة",
//     PricePackage: "السعر / حزمة",
//     TotalCost: "التكلفة الإجمالية",
//     Patch: "رقعة قماشية",
//     With: "مع",
//     Without: "بدون",
//     Label: "ضع الكلمة المناسبة",
//     Website: "موقع الكتروني",
//     SelectCategory: "اختر الفئة",
//     SelectTheme: "اختر نمطا",
//     SelectVendor: "حدد البائع",
//     SelectUnit: "وحدة مختارة",
//     StreetAddress1: "عنوان الشارع 1",
//     StreetAddress2: "عنوان الشارع 2",
//     BusinessAddress: "عنوان العمل",
//     City: "مدينة",
//     State: "حالة",
//     SocialMedia: "وسائل الاعلام الاجتماعية",
//     PostalCode: "الكود البريدى",
//     UodateForm: "نموذج التحديث",
//     Country: "بلد",
//     Light: "ضوء",
//     Dark: "الظلام (ليلة واسطة)",
//     UpdateFormString: " إضافة إلى تذكير لتذكير إذا تم تسليم المنتجات",
//     Note: "ملحوظة",
//     Email: "عنوان البريد الإلكتروني",
//     SelectCountry: "حدد الدولة",
//     MaxNoteCharacters: "أقصى 100 حرف",
//     EmailExample: " info@example.com: تحويلة",
//     MobileNo: "رقم المحمول.",
//     Work: "عمل",
//     Home: "الصفحة الرئيسية",
//     Main: "الأساسية",
//     Model: "نموذج رقم:",
//     Category: "الفئة",
//     Fax: "فاكس",
//     Custom: "مخصص",
//     Other: "آخر",
//     ChangeType: "تغيير نوع",
//     Signup: "سجل",
//     Login: "تسجيل الدخول",
//     Logout: "تسجيل خروج",
//     Name: "اسم",
//     Ignore: "تجاهل",
//     FullName: "الاسم الكامل",
//     Ignored: "تجاهل",
//     FirstName: "الاسم الاول",
//     LastName: "الكنية",
//     Active: "نشيط",
//     OrderDate: "تاريخ الطلب",
//     DateOfBirth: "تاريخ الولادة",
//     BusinessInformation: "معلومات العمل",
//     BusinessName: "الاسم التجاري",
//     Discounted: "مخفضة",
//     OnBackOrder: "تحت الطلب",
//     OutOfStock: "إنتهى من المخزن",
//     LowStock: "الأسهم منخفضة",
//     IncludeOnHold: "تشمل على عقد الأصناف",
//     Password: "كلمه السر",
//     RetypePassword: "اعد ادخال كلمة المرور",
//     CreateAccount: "انشاء حساب جديد",
//     AlreadyHaveAccount: "هل لديك حساب؟",
//     NewUser: "مستخدم جديد؟",
//     CreateYourAccount: "إنشاء حسابك مجانا.",
//     ForgotPassword: "هل نسيت كلمة المرور؟",
//     WelcomeBack: "مرحبا بعودتك!",
//     Agreement: "أنا أوافق على",
//     TOS: "شروط الخدمة",
//     And: "و",
//     SelectProduct: "حدد المنتج",
//     Providers: "مقدمي",
//     SelectProvider: "حدد مزود",
//     SelectVariantCategory: "اختر الفئة البديل",
//     AddMoreVariants: "إضافة المزيد من المتغيرات",
//     PrivacyPolicy: "سياسة خاصة",
//     OrLoginUsing: "أو تسجيل الدخول باستخدام",
//     English: "الإنجليزية",
//     Arabic: "عربى",
//     completeTheForm: "يرجى ملء النموذج.",
//     displayNameError: "ينبغي أن يكون اسم 5 أحرف على الأقل.",
//     displayEmailError: "البريد الإلكتروني ليست في الشكل الصحيح.",
//     displayPasswordError:
//       "يجب أن يحتوي على كلمة المرور الحد الأدنى ثمانية أحرف، رقم واحد وطابع خاص واحد.",
//     displayRetypePasswordError: "حقول كلمة المرور غير متطابقة.",
//     TosIsNotChecked: "يرجى قبول شروط الخدمة وسياسة الخصوصية قبل اعتماد النموذج",
//     RegistrationSuccessful: "نجاح عملية التسجيل. إرسال رسالة تحقق إلى حسابك.",
//     Confirm: "تؤكد",
//     Cancel: "إلغاء",
//     OnHold: "في الانتظار",
//     OnHoldSmall: "في الانتظار",
//     Dashboard: "لوحة القيادة",
//     Orders: "الطلب",
//     Bills: "فواتير",
//     Reports: "تقارير",
//     ProductsServices: "المنتجات والخدمات",
//     PreOrder: "طلب مسبق",
//     PreOrderSmall: "طلب مسبق",
//     Customers: "الزبائن",
//     Vendors: "الباعة",
//     Vendor: "بائع",
//     VendorAdd: "إضافة بائع جديد",
//     VendorEdit: "تحرير بائع",
//     VendorDetail: "بائع التفاصيل",
//     Employees: "الموظفين",
//     Analysis: "تحليل",
//     NoOfEmployee: "عدد الموظفين",
//     LastBillDate: "بيل آخر تاريخ",
//     LastBillNo: "آخر مشروع القانون رقم",
//     LastTransaction: "آخر صفقة:",
//     LastUpdated: "آخر تحديث",
//     NotRecorded: "غير مسجل",
//     ContactSupport: "اتصل بنا / دعم",
//     VendorInformation: "معلومات البائع",
//     RepresentativesInformation: "معلومات النواب",
//     VendorHistory: "بائع التاريخ",
//     AddLabel: "إضافة تسمية",
//     TransactionDate: "تاريخ الصفقة",
//     StartDate: "تاريخ البدء",
//     EndDate: "تاريخ الانتهاء",
//     SelectDate: "حدد تاريخ",
//     FilterByLabel: "تصفية حسب تسمية",
//     SelectLabel: "حدد التسمية",
//     Apply: "تطبيق",
//     Reset: "إعادة تعيين",
//     AddNew: "اضف جديد",
//     ProductEdit: "تحرير المنتج",
//     ProductType: "نوع المنتج",
//     Product: "المنتج",
//     Variant: "مختلف",
//     Variants: "المتغيرات",
//     Service: "الخدمات",
//     Package: "صفقة",
//     Packages: "حزم",
//     Settings: "الإعدادات",
//     UserProfile: "ملف تعريفي للمستخدم",
//     Themes: "المواضيع"
//   }
// });
