export const dictionary = {
  // "Welcome Back": "",
  // "Forgot Password": "",
  // "Email Address": "",
  // Password: "",
  // "Log In": "",
  // "New User": "",
  // "Create Your Account For Free": "",
  // "Privacy policy": "",
  // "Term and condition": "",
  // "Contact us": "",
  // "Create new account": "",
  // "Already have an account": "",
  // "My Account": "",
  // Logout: "",
  // dashboard: "",
  // "Add New GraphLast": "",
  // Sales: "",
  // "Profit and loss": "",
  // Performance: "",
  // Expenses: "",
  // "Overhead cost": "",
  // Time: "",
  // "Contact List": "",
  // Customers: "",
  // Vendors: "",
  // Reminders: "",
  // Inventory: "",
  // "Product Name": "",
  // Quantity: "",
  // Ends: "",
  // "Customer Name": "",
  // Currency: "",
  // "Street Address 1": "",
  // "Street Address 2": "",
  // City: "",
  // "Phone No": "",
  // "Issue date": "",
  // "Due date": "",
  // State: "",
  // Country: "",
  // "Postal Code": "",
  // "Add item": "",
  // "Order detail": "",
  // Generate: "",
  // Preview: "",
  // Back: "",
  // "Paid by customer": "",
  // Sar: "",
  // "Add New Bills": "",
  // "Bills Detail": "",
  // Status: "",
  // "Total Balance": "",
  // "Balance Due": "",
  // "Due Date": "",
  // "Issue Date": "",
  // "Bill No": "",
  // "Add new bills": "",
  // Bills: "",
  // "One Time": "",
  // Recurring: "",
  // "Bills Item": "",
  // "Create New item": "",
  // "Select item": "",
  // Add: "",
  // Included: "",
  // Name: "",
  // Age: "",
  // Address: "",
  // Salary: "",
  // "Bill Paid": "",
  // Reports: "",
  // "All categories": "",
  // Anually: "",
  // "2018": "",
  // order: "",
  // Revenue: "",
  // "VAT REPORT": "",
  // "INCOME STATEMENT": "",
  // Total: "",
  // "View More": "",
  // Report: "",
  // "Products/Services": "",
  // Filter: "",
  // "Add New Entry": "",
  // Type: "",
  // "Price range": "",
  // "Purchase Date": "",
  // "Expiration Date": "",
  // "Close Filters": "",
  // Apply: "",
  // Reset: "",
  // Active: "",
  // Discontinued: "",
  // "On Back Order": "",
  // "Out of Stock": "",
  // "Low Stock": "",
  // "Include On Hold": "",
  // Items: "",
  // "On Hold": "",
  // Expiration: "",
  // "Pre Order": "",
  // Price: "",
  // QTY: "",
  // Email: "",
  // Day: "",
  // Month: "",
  // Year: "",
  // "Visa Number": "",
  // "Starting Date": "",
  // "Working Schedule": "",
  // "Set Schedule": "",
  // "Emploment Term": "",
  // "Part Time": "",
  // "Full Time": "",
  // "Basic Salary": "",
  // "Extra Hours Salary": "",
  // Accomodation: "",
  // "Insurance Allowance": "",
  // "Insurance Deduction": "",
  // "Communication Allowance": "",
  // "Transportation Allowance": "",
  // "Meal Allowance": "",
  // Gratuities: "",
  // "Other Compesation Allowance": "",
  // "Test Monthly Salary": "",
  // Save: "",
  // Discard: "",
  // Employees: "",
  // Analysis: "",
  // Trends: "",
  // Comparison: "",
  // "Customize your graph": "",
  // "Sale & Expenses": "",
  // "Profit & Loss": "",
  // "Pin to dashboard": "",
  // "All Categories": "",
  // "All product Categories": "",
  // "One Time Bill": "",
  // "Contact Us / Support": "",
  // Send: "",
  // FAQ: "",
  // Subscription: "",
  // "Subscription/Services": "",
  // "See Subscription": "",
  // "Account Overview": "",
  // "Member Since": "",
  // "Subscription Status": "",
  // "Account Status": "",
  // "Cancel Trial": "",
  // "Subscribe Now": "",
  // "Plan details": "",
  // "Bedayeah Free Trial": "",
  // "Next billing date": "",
  // "Cancel Plan": "",
  // "Upgrade Plan": "",
  // "User account will still be active unitll the end of current billing period":
  //   "",
  // Actions: "",
  // "Most Popular": "",
  // ANNUALLY: "",
  // QUARTERLY: "",
  // Monthly: "",
  // "Quarterly Plan": "",
  // "Insert Promocode": "",
  // "Additional Users": "",
  // username: "",
  // "Retype Password": "",
  // Privileges: "",
  // Orders: "",
  // "Invite user by email": "",
  // Cancel: "",
  // "User Profile": "",
  // "Additional User": "",
  // "Sign In and Security": "",
  // "Theme Options": "",
  // Preferences: "",
  // Notification: "",
  // "Date of Birth": "",
  // "Mobile No": "",
  // "Business Information": "",
  // "Business Name": "",
  // "No .of Employee": "",
  // "Vat Acc. No": "",
  // "Commercial Registration Number": "",
  // "Commercial Registration Number (CRN)": "",
  // Business: "",
  // Website: "",
  // "Add More": "",
  // "Social Media": "",
  // "Invite User": "",
  // "General Settings": "",
  // "Change Password / Email Address": "",
  // "Do you want to apply all setting with new email address": "",
  // "Do you want to apply all setting with new email address ?": "",
  // Light: "",
  // "Dark(Night mode)": "",
  // "Add Shipping": "",
  // "Add Discount": "",
  // "Order Total": "",
  // "Success!": "",
  // "Profile updated successfully": "",
  // "Profile updated successfully.": "",
  // VAT: "",
  // "Default VAT": "",
  // Regional: "",
  // "Time Zone": "",
  // "Date Format": "",
  // "Currency Format": "",
  // SAR: "",
  // "Start Page": "",
  // "Default Page": "",
  // "Company Logo": "",
  // "Work Schedule": "",
  // "Work Days": "",
  // Start: "",
  // End: "",
  // Sunday: "",
  // Monday: "",
  // Tuesday: "",
  // Wednesday: "",
  // Thursday: "",
  // Friday: "",
  // Saturday: "",
  // "Working days": "",
  // "UnprocessableEntityError!": "",
  // "The request body is invalid. See error object `details` property for more info.":
  //   "",
  // "Religious holiday": "",
  // Notifications: "",
  // "Email Notification": "",
  // "Send summary": "",
  // "subscription expiration/reminder to renew email": "",
  // "Email me when I have a new notification": "",
  // "Send advice email": "",
  // "Send invoice alert": "",
  // "Desktop Notification": "",
  // "Enable desktop notification": "",
  // BEDAYEAH: "",
  // "you are unauthorized": "",
  // "Bills with this id not found": "",
  // "fullName is required for customer": "",
  // "Customer with name already exists": "",
  // "Customer with this id not found!": "",
  // "email is required for sending link": "",
  // "Invalid email or password": "",
  // "Authorization header not found.": "",
  // "Authorization header is not of type Bearer.": "",
  // "Error generating token": "",
  // "Error verifying token": "",
  // "We have email required please use facebook account which have verified email!":
  //   "",
  // "Email is already taken": "",
  // "invalid Email": "",
  // "Name should be less than 50 chracters!": "",
  // "name required": "",
  // "User with id not found!": "",
  // "user with this email not found": "",
  // "Label with this id not found": "",
  // "Departments with this id not found": "",
  // "Employees with this id not found": "",
  // "Positions with this id not found": "",
  // "Error comes in uploading image": "",
  // "return status required return products": "",
  // "return only applied on completed order": "",
  // "Payment order of this order should be paid": "",
  // "you cannot update status of order from complete to ": "",
  // "Orders with this id not found": "",
  // "order with this order no not found!": "",
  // "order status should be from list ": "",
  // "it could not be canceled because it is completed": "",
  // "Status should be complete before exchange": "",
  // "exchange Products required for exchaging": "",
  // "Category with this id not found": "",
  // "Unit with this id not found": "",
  // "Product with this id not found": "",
  // "fullName is required for vendor": "",
  // "parentId is required for creating representative for vendor": "",
  // "Vendor with this user name already exists": "",
  // "Vendor with this id not found!": "",
  // sendingEmail: "",
  // "Current password is incorrect!": "",
  // "Authorization header value has too many parts. It must follow the pattern: 'Bearer xx.yy.zz' where xx.yy.zz is a valid JWT token.":
  //   "",
  // "Password should contain minimum eight characters, at least one letter, one number and one special character!":
  //   "",
  // "Product Name": "اسم المنتج",

  // Orignal Arabic conversion start from here the arabic that is on top is just for test purpose
  "Welcome Back": "مرحبا بعودتك",
  "Forgot Password": "نسيت كلمة المرور",
  "Email Address": "عنوان البريد الإلكتروني",
  Password: "كلمة المرور",
  "Log In": "تسجيل الدخول",
  "New User": "مستخدم جديد",
  "Create Your Account For Free": "انشاء حسابك مجانا",
  "Privacy policy": "سياسة الخصوصية",
  "Term and condition": "اتفاقية شروط واحكام استخدام موقع",
  "Contact us": "تواصل معنا",
  "Create new account": "انشاء حساب",
  "Already have an account": "عملاء مالقرو السابقين",
  "My Account": "حسابي",
  Logout: "تسجيل خروج",
  "Contact us": "تواصل معنا",
  "Create new account": "انشاء حساب",
  "Already have an account": "عملاء مالقرو السابقين",
  "My Account": "حسابي",
  Dashboard: "لوحة القيادة",
  dashboard: "لوحة القيادة",
  Sales: "مبيعات",
  "Profit and loss": "الربح والخسارة",
  Performance: "أداء",
  Expenses: "نفقات",
  "Overhead cost": "التكاليف العامة",
  Time: "الوقت",
  "Contact List": "قائمة الإتصال",
  Customers: "عملاء",
  undefined: "زباين",
  Vendors: "الباعة",
  Reminders: "تذكير",
  Inventory: "المخزون",
  "Product Name": "اسم المنتج",
  Quantity: "كمية",
  "Customer Name": "اسم العميل",
  "Contact us": "تواصل معنا",
  "Create new account": "انشاء حساب",
  "Already have an account": "عملاء مالقرو السابقين",
  "My Account": "حسابي",
  "Profit and loss": "الربح والخسارة",
  "Overhead cost": "التكاليف العامة",
  Time: "الوقت",
  "Contact List": "قائمة الإتصال",
  Vendors: "الباعة",
  Reminders: "تذكير",
  Inventory: "المخزون",
  "Product Name": "اسم المنتج",
  Quantity: "كمية",
  "Customer Name": "اسم العميل",
  Currency: "عملة",
  "Street Address 1": "عنوان 1",
  "Street Address 2": "عنوان 2",
  City: "المدينة",
  "Phone No": "رقم الجوال",
  "Issue date": " تاريخ الانتاج",
  "Due date": "تاريخ الاستحقاق",
  Country: "البلد",
  "Add item": "اضافة عنصر",
  "Order detail": "تفاصيل الطلب",
  Generate: "انشاء",
  Preview: "معاينة",
  Back: "رجوع",
  "Paid by customer": "مدفوع",
  Sar: "ريال سعودي",
  "Add New Bills": "اضافة فواتير جديدة",
  "Bills Detail": "تفاصيل الفاتورة",
  Status: "الحالة",
  "Total Balance": "إجمالي الرصيد",
  "Balance Due": "الرصيد المستحق",
  "Due Date": "تاريخ الاستحقاق",
  "Contact Information": "تاريخ الاستحقاق",
  "Bill No": "رقم الفاتوره",
  "Add new bills": "",
  Bills: "فواتير",
  "One Time": "مره واحده",
  Recurring: "متكرر",
  "Bills Item": "بند الفواتير",
  "Create New item": "إنشاء عنصر جديد",
  "Select item": "اختيار العناص",
  "Create New item": "إنشاء عنصر جديد",
  "Select item": "اختيار العناصر",
  Add: "أضف",
  Included: "مشمول",
  Name: "اسم",
  Age: "العمر",
  Address: "عنوان",
  Salary: "راتب",
  "Bill Paid": "فاتورة مدفوعة",
  Reports: "التقارير",
  "All categories": "",
  Anually: "سنوي",
  "2018": "2018",
  order: "طلب",
  Revenue: "دخل",
  "VAT REPORT": "تقرير الضريبة",
  "INCOME STATEMENT": "قوائم الدخل",
  Total: "المجموع",
  "View More": "مشاهدة المزيد",
  Report: "تقرير",
  "Products/Services": "منتجات / خدمات",
  Filter: "فلتر",
  "Add New Entry": "أضف مدخل جديد",
  Type: "نوع",
  "Price range": "نطاق السعر",
  "Purchase Date": "تاريخ الشراء",
  "Close Filters": "اغلاق الفلتر",
  Apply: "تطبيق",
  Reset: "إعادة تعيين",
  Active: "نشط",
  Discontinued: "متوقف انتاجها",
  "On Back Order": "",
  "Out of Stock": "غير متوفر",
  "Low Stock": "منخفض المخزون",
  "Include On Hold": "",
  Items: "العناصر",
  "On Hold": "في الانتظار",
  Expiration: "تاريخ الانتهاء",
  "Pre Order": "طلب مسبق",
  Price: "السعر",
  QTY: "كمية",
  Email: "ايميل",
  Day: "يوم",
  Month: "شهر",
  Year: "سنة",
  "Visa Number": "رقم الفيزا",
  "Starting Date": "تاريخ البدء",
  "Working Schedule": "جدول العمل",
  "Set Schedule": "ضبط الجدول",
  "Emploment Term": "",
  "Part Time": "دوام جزئى",
  "Full Time": "دوام كامل",
  "Basic Salary": "الراتب الاساسي",
  "Extra Hours Salary": "",
  Accomodation: "",
  "Insurance Allowance": "",
  "Insurance Deduction": "",
  "Communication Allowance": "",
  "Transportation Allowance": "",
  "Meal Allowance": "",
  Gratuities: "الإكراميات",
  "Other Compesation Allowance": "",
  "Test Monthly Salary": "",
  Save: "حفظ",
  Discard: "تجاهل",
  Employees: "الموظفين",
  Analysis: "تحليل",
  Trends: "",
  Comparison: "مقارنة",
  "Customize your graph": "",
  "Sale & Expenses": "البيع والمصاريف",
  "Profit & Loss": "خسارة و الأرباح",
  "Pin to dashboard": "تثبيت على لوحة القيادة",
  "All Categories": "",
  "All product Categories": "جميع فئات المنتجات",
  "One Time Bill": "فاتورة لمرة واحدة",
  "Contact Us / Support": "اتصل بنا / الدعم",
  Send: "إرسال",
  FAQ: "",
  Subscription: "اشتراك",
  "Subscription/Services": "الاشتراك / الخدمات",
  "See Subscription": "",
  "Account Overview": "نظرة عامة على الحساب",
  "Member Since": "عضو منذ",
  "Subscription Status": "حالة الاشتراك",
  "Account Status": "حالة الحساب",
  "Cancel Trial": "إلغاء التجربة",
  "Subscribe Now": "إشترك الآن",
  "Plan details": "تفاصيل الخطة",
  "Bedayeah Free Trial": "تجربة مجانية",
  "Next billing date": "",
  "Cancel Plan": "إلغاء الخطة",
  "Upgrade Plan": "",
  "User account will still be active unitll the end of current billing period":
    "سيظل حساب المستخدم نشطًا حتى نهاية",
  Actions: "",
  "Most Popular": "الأكثر شهرة",
  ANNUALLY: "سنوي",
  QUARTERLY: "ربعي",
  Monthly: "شهري",
  "Quarterly Plan": "",
  "Insert Promocode": "",
  "Additional Users": "المستخدمون الإضافيون",
  username: "اسم المستخدم",
  "Retype Password": "اعد كتابة كلمة المرور",
  Privileges: "",
  Orders: "الطلبات",
  "Invite user by email": "اضافة مستخدم عبر الايميل",
  Cancel: "الغاء",
  "User Profile": "",
  "Sign In and Security": "تسجيل الدخول والأمن",
  "Theme Options": "خيارات ال",
  Preferences: "خيارات",
  Notification: "تنبيهات",
  "Date of Birth": "تاريخ الميلاد",
  "Mobile No": "رقم الجوال",
  "Business Information": "معلومات العمل",
  "Business Name": "اسم العمل",
  "No .of Employee": "عدد الموظفين",
  "Vat Acc. No": "رقم حساب الVAT",
  "Commercial Registration Number": "رقم السجل التجاري",
  "Commercial Registration Number (CRN)": "",
  Business: "",
  Website: "الموقع الكتروني",
  "Add More": "اضافة المزيد",
  "Social Media": "وسائل التواصل الاجتماعي",
  "Invite User": "دعوة مستخدم",
  "General Settings": "الاعدادات العامة",
  "Change Password / Email Address": "تغير كلمة المرور / البريد الالكتروني",
  "Do you want to apply all setting with new email address": "",
  "Do you want to apply all setting with new email address ?": "",
  Light: "فاتح",
  "Dark(Night mode)": "غامق (الوضع اليلي)",
  "Add Shipping": "اضافة شحن",
  "Add Discount": "اضافة تخفيض",
  "Order Total": "الطلب الكلي",
  "Success!": "نجاح",
  "Profile updated successfully": "تم تحديث الملف الشخصي بنجاح",
  VAT: "",
  "Default VAT": "",
  English: "",
  "Time Zone": "",
  "Date Format": "",
  "Currency Format": "",
  English: 'SAR:"",',
  Arabic: "",
  "Suggested English": "",
  "Start Page": "",
  "Default Page": "",
  "Company Logo": "شعار الشركة",
  English: "جدول العمل",
  "Work Days": "ايام العمل",
  Start: "بداية",
  End: "نهاية",
  Sunday: "الأحد",
  Monday: "الإثنين",
  Tuesday: "الثلاثاء",
  Wednesday: "الأربعاء",
  Thursday: "الخميس",
  Friday: "الجمعة",
  Saturday: "السبت",
  "Working days": "أيام العمل",
  "UnprocessableEntityError!": "خطأ غير قابل للمعالجة",
  "The request body is invalid. See error object `details` property for more info.":
    "",
  "Religious holiday": "إجازة دينية",
  Notifications: "اشعارات",
  "Email Notification": "اشعارات البريد الالكتروني",
  "Send summary": "ارسل ملخص",
  "subscription expiration/reminder to renew email":
    "انتهاء الاشتراك/تذكيرلتجديد البريد الالكتروني",
  "Email me when I have a new notification":
    "أرسل لي رسالة على بريد الالكتروني عندما يكون لدي اشعار جديد",
  "Send advice email": "أرسل لي رسائل النصائح على البريد الالكتروني",
  "Send invoice alert": "ارسل لي تنبيه الايصال",
  "Desktop Notification": "تنبيهات سطح المكتب",
  "Enable desktop notification": "تفعيل تنبيهات سطح المكتب",
  BEDAYEAH: "بداية",
  "you are unauthorized": "أنت غير مصرح",
  "Bills with this id not found": "لم يتم العثور على الفواتير بهذا المعرف",
  "fullName is required for customer": "الاسم الكامل مطلوب للعميل",
  "Customer with name already exists": "العميل بهذا الاسم مسجل مسبقا",
  "Customer with this id not found!": "العميل غير موجود بهذا المعرف",
  "email is required for sending link": "البربد الالكتروني مطلوب لإرسال الرابط",
  "Invalid email or password": "خطأ في البريد الكتروني أو رقم السري",
  "Authorization header not found.": "لم يتم العثور على رأس التفويض",
  "Authorization header is not of type Bearer": "",
  "Error generating token": "حدث خطأ عند انشاء الرمز المميز",
  "Error verifying token": "خطأ في التحقق من الرمز المميز",
  "We have email required please use facebook account which have verified email!":
    "",
  "Email is already taken": "البربد الالكتروني مستخدم سابقا",
  "invalid Email": "البريد الالكتروني خاطئ",
  "Name should be less than 50 chracters!": "الاسم يحب ان يكون أقل من ٥٠ رمز",
  "name required": "الاسم مطلوب",
  "User with id not found!": "الاسم بهذا المعرف غير موجود",
  "user with this email not found": "الاسم بهذا البريد لالكتروني غير موجود",
  "Label with this id not found":
    "لم يتم العثور على التصنيفات التي تحمل هذا المعوف",
  "Departments with this id not found":
    "لم يتم العثور على الأقسام التي تحمل هذا المعرّف",
  "Employees with this id not found": "لم يتم العثور على موظفين بهذا المعرف",
  "Positions with this id not found": "لم يتم العثور على منصب بهذا المعرف",
  "Error comes in uploading image": "خطأ في تحميل الصورة",
  "return status required return products": "حالة الارجاع تتطلب ارجاع المنتج",
  "return only applied on completed order":
    "الاسترجاع يتم فقط عند الطلبات المكتملة",
  "Payment order of this order should be paid": "",
  "you cannot update status of order from complete to": "",
  "Orders with this id not found": "الطلبات مع هذا المعرف غير موجودة",
  "order with this order no not found!": "",
  "order status should be from list": "يجب أن تكون حالة الطلب من القائمة",
  "it could not be canceled because it is completed":
    "لا يمكن إلغاؤها لأنه مكتملة",
  "Status should be complete before exchange":
    "يجب أن تكتمل الحالة قبل الاستبدال",
  "exchange Products required for exchaging": "",
  "Category with this id not found":
    "لم يتم العثور على الفئة التي تحمل هذا المعرف",
  "Unit with this id not found":
    "لم يتم العثور على الوحدة التي تحمل هذا المعرف",
  "Product with this id not found": "لم يتم العثور على المنتج بهذا المعرف",
  "fullName is required for vendor": "الاسم الكامل مطلوب للبائع",
  "parentId is required for creating representative for vendor": "",
  "Vendor with this user name already exists": "المورد بهذا الاسم مسجل مسبقا",
  "Vendor with this id not found!": "لم يتم العثور على المورد بهذا المعرف!",
  sendingEmail: "إرسال البريد الإلكتروني",
  "Current password is incorrect!": "الرقم السري الحالي غير صحيح",
  "Authorization header value has too many parts. It must follow the pattern: 'Bearer xx.yy.zz' where xx.yy.zz is a valid JWT token.":
    "",
  "Password should contain minimum eight characters, at least one letter, one number and one special character!":
    "يجب أن تحتوي كلمة المرور على ثمانية أحرف على الأقل ، حرف واحد على الأقل ، ورقم واحد ، و رمز خاص واحد!",
};
